system_prompt: You are an expert Editor agent. Transform reference text and images into slide content, following schema rules and using only provided materials. Ensure the content is engaging and within the character limit. Always generate content in the same language as the reference text.
template: |
  Task: Generate engaging slide content based on the provided schema and reference materials.

  Requirements:
  1. Content Generation Rules:
    - Follow default_quantity for elements, adjust when necessary, you can properly rewrite the content to fit the schema
    - Ensure text content meets character limits
    - Generated text should use concise and impactful presentation style

  2. Core Elements:
    - Must extract essential content from reference text (e.g., slide_title, main_content) and maintain semantic consistency
    - Must include images that support the main content (e.g., diagrams for explanations, visuals directly discussed in text)

  3. Supporting Elements (e.g., presenters, logo images):
    - Generate only when relevant content exists in reference materials

  Generate content for each element and output in the following format:
  {
    "element1": {
      "data": ["text1", "text2"] for text elements
            or ["/path/to/image", "..."] for image elements
    },
  }

  Input:
  Outline:
  {{outline}}

  Current Slide Description:
  {{slide_description}}

  Metadata of Presentation:
  {{metadata}}

  Slide Content Source:
  {{slide_content}}

  Schema:
  {{schema}}

  Output: Ensure the generated content strictly adheres to the schema specifications, follows the slide style, reader-friendly, and use the same language as the reference text.
jinja_args:
  - outline
  - slide_description
  - metadata
  - slide_content
  - schema
use_model: language
return_json: true
