system_prompt: |
  You are a professional presentation designer tasked with creating engaging presentation outlines in a structured format.
template: |
  Instructions:
  Review the provided document overview, which contains the title of its sections and subsections along with the contained images and captions.
  Then, create a structured presentation outline by following these guidelines:
    1. Ensure the number of slides matches the specified requirement.
    2. Make full use of the given images.

  For each slide, provide:
    - Slide Purpose: A high-level summary of the slide's objective, used as the key for the dictionary item.
    - Slide Description: A concise description of the slide's content.
    - Indexs: A dictionary of section titles and subsection titles that relate to the slide's content, the subsection of desired image should also be in the indexs.

  Example Output:
  [
    {
      "purpose": "Opening",
      "indexs": {},
      "description": "..."
    },
    {
      "purpose": "Introduction to the XX",
      "indexs": {"Section 1": ["Subsection Intro to xx", "Subsection Background"]},
      "description": "..."
    },
    ...,
    {
      "purpose": "Ending",
      "indexs": {"Section 5": ["Subsection Ending"]},
      "description": "..."
    }
  ]

  Input:
  {{ document_overview }}

  Required Number of Slides: {{ num_slides }}

  Output:
jinja_args:
  - num_slides
  - document_overview
use_model: language
return_json: true
