system_prompt: You are an helpful assistant that helps to generate slide content for a presentation.
template: |
  Task: Generate engaging slide content based on the provided schema and reference materials.

  Requirements:
  1. Element Quantity:
    - For image elements or elements with `default_quantity=1` in the schema (e.g., main title), always generate number of items less than or equal to the default_quantity.
    - For other elements (e.g., bulleted list), use the schema's default_quantity as a reference target—aim to generate content that approximates this quantity while ensuring completeness and readability of the key information from the source material.
    - Make best effort to generate suitable content, only delete them when no proper content can be generated.

  2. Content Extraction and Refinement
    - Rewrite content from reference text for each schema element, ensuring accurate meaning and semantic consistency. Try to use vocabulary from the provided materials to ensure consistency.
    - You can use common abbreviations (e.g., etc., et al., TOC, LLM) for brevity where appropriate, but **do not invent new abbreviations** or fabricate information not present in the source material.
    - Rewrite the content to the language specified in the input, and strictly adhere to the character limits (`suggested_characters`) in the schema for each element.

  Output Format:
  {
    "elements": [
      {
        "name": "element_name",
        "data": ["content1", "content2", "..."]
        // Array of strings for text elements in specified language
        // OR array of image paths for image elements: ["/path/to/image1.jpg", "/path/to/image2.png"]
      }
    ]
  }

  Input:
  ===Presentation Outline===:
  {{outline}}

  ===Metadata of the Presentation===:
  {{metadata}}

  ===Description of the Current Slide===:
  {{slide_description}}

  ===Retrieved Content===:
  {{slide_content}}

  ===Schema===:
  {{schema}}

  ===Language===: given in ISO-639 format
  {{language}}

  Output: Ensure all the elements in the schema are generated even if the content is empty, and use the language specified in the input.
jinja_args:
  - outline
  - slide_description
  - metadata
  - slide_content
  - schema
  - language
use_model: language
return_json: true
